import Link from 'next/link'
import PageFooter from '@/app/components/PageFooter'

export const metadata = { title: 'About — Dreams & Omens' }

export default function AboutPage() {
  return (
    <main style={{ maxWidth: 480, margin: '0 auto', padding: '40px 20px' }}>

      <header style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 32 }}>
        <Link href="/" style={{ color: 'var(--owl-brown)', fontSize: 22, textDecoration: 'none' }}>←</Link>
        <h1 className="text-title-l" style={{ color: 'var(--ink)' }}>About</h1>
      </header>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

        <div style={{ textAlign: 'center', marginBottom: 8 }}>
          <div style={{ fontSize: 56, marginBottom: 12 }}>🦉</div>
          <h2 className="text-title-xl" style={{ color: 'var(--ink)', marginBottom: 8 }}>Dreams &amp; Omens</h2>
        </div>

        <div className="card-primary">
          <h3 className="text-title-m" style={{ color: 'var(--ink)', marginBottom: 12 }}>We built this because Googling dreams is broken.</h3>
          <p className="text-body" style={{ color: 'var(--text-secondary)', lineHeight: '26px', marginBottom: 14 }}>
            You wake up from something vivid — strange, emotional, hard to shake. You type a few
            words into a search bar. You get a list. &ldquo;Dreaming about water means
            emotions.&rdquo; Cool. Which emotions? Why now? What does <em>your</em> water dream mean?
          </p>
          <p className="text-body" style={{ color: 'var(--text-secondary)', lineHeight: '26px', marginBottom: 14 }}>
            Dreams &amp; Omens was built to answer the question Google can&apos;t: what does this
            specific dream mean for me, right now?
          </p>
          <p className="text-body" style={{ color: 'var(--text-secondary)', lineHeight: '26px', marginBottom: 14 }}>
            We blend psychology, pattern-spotting, and timeless symbolism to give you
            interpretations that feel personal — because they are. You describe what happened.
            We reflect it back to you in a way that actually makes you think.
          </p>
          <p className="text-body" style={{ color: 'var(--ink)', fontWeight: 600, lineHeight: '26px' }}>
            No fortune-telling. No vague platitudes. Just thoughtful reflection, personalized to
            what you actually dreamed.
          </p>
        </div>

        <div className="card-primary">
          <h3 className="text-title-m" style={{ color: 'var(--ink)', marginBottom: 10 }}>Anonymous &amp; private</h3>
          <p className="text-body" style={{ color: 'var(--text-secondary)' }}>
            No account is required to get started. Free interpretations are processed in real time and
            stored only on your device. We never sell your data. If you choose to create an account,
            your history is encrypted in transit and stored securely in the cloud.
          </p>
        </div>

        <div className="card-secondary">
          <p className="text-helper" style={{ color: 'var(--owl-brown)' }}>
            <strong>Disclaimer:</strong> Dreams &amp; Omens is for entertainment and personal reflection
            only. Interpretations are generated by our service and do not constitute medical, psychological,
            legal, or financial advice. If you are experiencing distress, please seek help from a
            qualified professional.
          </p>
        </div>

      </div>

      <footer style={{ textAlign: 'center', marginTop: 40 }}>
        <PageFooter />
      </footer>

    </main>
  )
}
