import Link from 'next/link'
import PageFooter from '@/app/components/PageFooter'

export const metadata = { title: 'Terms of Service — Dreams & Omens' }

const LAST_UPDATED = 'April 12, 2026'

export default function TermsPage() {
  return (
    <main style={{ maxWidth: 480, margin: '0 auto', padding: '40px 20px' }}>

      <header style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 32 }}>
        <Link href="/" style={{ color: 'var(--owl-brown)', fontSize: 22, textDecoration: 'none' }}>←</Link>
        <h1 className="text-title-l" style={{ color: 'var(--ink)' }}>Terms of Service</h1>
      </header>

      <p className="text-helper" style={{ color: 'var(--owl-brown)', marginBottom: 28 }}>
        Last updated: {LAST_UPDATED}
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>

        <Section title="Acceptance of terms">
          By accessing or using DreamsAndOmens.com (&ldquo;the Service&rdquo;), you agree to be bound by
          these Terms of Service. If you do not agree, please do not use the Service.
        </Section>

        <Section title="Entertainment purposes only">
          <strong style={{ color: 'var(--ink)' }}>The Service is provided for entertainment and personal
          reflection only.</strong> Our interpretations are not a substitute for professional
          medical, psychological, psychiatric, legal, or financial advice. Never disregard professional
          advice or delay seeking it because of something you read in an interpretation.
          Dreams &amp; Omens expressly disclaims any liability arising from reliance on content
          generated by the Service.
        </Section>

        <Section title="Eligibility">
          You must be at least 13 years old to use the Service. By using the Service, you represent
          that you meet this requirement. Users between 13 and 18 require parental or guardian consent.
        </Section>

        <Section title="Your account">
          You are responsible for maintaining the confidentiality of your account credentials
          and for all activity under your account. Notify us immediately at{' '}
          <a href="mailto:hello@dreamsandomens.com" style={{ color: 'var(--cedar)' }}>
            hello@dreamsandomens.com
          </a>{' '}
          if you suspect unauthorized access. We reserve the right to terminate accounts that
          violate these terms.
        </Section>

        <Section title="Acceptable use">
          You agree not to:
          <ul style={{ marginTop: 8, paddingLeft: 20 }}>
            <li style={{ marginBottom: 6 }}>Submit content that is illegal, harmful, or violates the rights of others</li>
            <li style={{ marginBottom: 6 }}>Attempt to reverse-engineer, scrape, or overload the Service</li>
            <li style={{ marginBottom: 6 }}>Use the Service to generate content that harasses, threatens, or demeans others</li>
            <li style={{ marginBottom: 6 }}>Circumvent usage limits or account restrictions through technical means</li>
          </ul>
        </Section>

        <Section title="Subscriptions and billing">
          Paid subscriptions (Basic and Reflect+) are billed monthly via Stripe. Subscriptions
          auto-renew until cancelled. You may cancel at any time from the Settings screen.
          Cancellation takes effect at the end of the current billing period. We do not offer
          prorated refunds for partial months. Introductory pricing is available for new subscribers
          only and applies to the first billing period.
        </Section>

        <Section title="Intellectual property">
          The Dreams &amp; Omens name, logo, design, and original content are owned by us and protected
          by intellectual property law. Interpretation text generated by the Service is provided to you for
          personal use only. You may not redistribute or commercially exploit interpretations
          without our written consent.
        </Section>

        <Section title="User content">
          You retain ownership of the dream and omen descriptions you submit. By submitting content,
          you grant us a limited license to process it through our Service solely to generate
          your interpretation. We do not claim ownership over your submissions.
        </Section>

        <Section title="Disclaimer of warranties">
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
          express or implied. We do not warrant that the Service will be uninterrupted, error-free,
          or that interpretations will be accurate, complete, or suitable for any purpose.
        </Section>

        <Section title="Limitation of liability">
          To the maximum extent permitted by law, Dreams &amp; Omens shall not be liable for any
          indirect, incidental, special, consequential, or punitive damages arising from your
          use of the Service, including reliance on any interpretation provided.
        </Section>

        <Section title="Changes to terms">
          We may update these terms at any time. Continued use of the Service after changes
          are posted constitutes acceptance. We will update the &ldquo;Last updated&rdquo; date above
          when changes are made.
        </Section>

        <Section title="Governing law">
          These terms are governed by the laws of the United States. Any disputes shall be
          resolved through binding arbitration, except where prohibited by law.
        </Section>

        <Section title="Contact">
          Questions about these terms? Email{' '}
          <a href="mailto:hello@dreamsandomens.com" style={{ color: 'var(--cedar)' }}>
            hello@dreamsandomens.com
          </a>.
        </Section>

      </div>

      <footer style={{ textAlign: 'center', marginTop: 40 }}>
        <PageFooter />
      </footer>

    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="card-primary">
      <h2 className="text-title-m" style={{ color: 'var(--ink)', marginBottom: 10 }}>{title}</h2>
      <div className="text-body" style={{ color: 'var(--text-secondary)', lineHeight: '24px' }}>
        {children}
      </div>
    </div>
  )
}
